name: React build and deploy
on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Verify Build Output # 빌드 결과 확인
        run: ls -la dist/ # 빌드 폴더가 제대로 생성되었는지 확인

      - name: Deploy to S3 # S3에 배포
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist/ s3://cammoabucket  # 본인의 bucket 이름으로 변경, build가 된 경로로 설정
